fruits = []
f1 = input("Enter fruits name")
f2 = input("Enter fruits name")
f3 = input("Enter fruits name")
f4 = input("Enter fruits name")
f5 = input("Enter fruits name")
f6 = input("Enter fruits name")
f7 = input("Enter fruits name")
fruits.append(f1)
fruits.append(f2)
fruits.append(f3)
fruits.append(f4)
fruits.append(f5)
fruits.append(f6)
fruits.append(f7)
print(fruits)