Marks = []
f1 = int(input("Enter Marks :"))
f2 = int(input("Enter Marks :"))
f3 = int(input("Enter Marks :"))
f4 = int(input("Enter Marks :"))
f5 = int(input("Enter Marks :"))
f6 = int(input("Enter Marks :"))
Marks.append(f1)
Marks.append(f2)
Marks.append(f3)
Marks.append(f4)
Marks.append(f5)
Marks.append(f6)
Marks.sort()
print(Marks)